# Use postgres/example user/password credentials
version: '3.4'

services:

  sandglass_postgres:
    container_name: sandglass_postgres
    image: postgres:16.2-alpine
    restart: always
    env_file:
      - .env.prod
    volumes:
      - sandglass_postgres:/var/lib/postgresql
    expose:
      - 5432:5432
    networks:
      - sandglass


  sandglass_app:
    container_name: sandglass_app
    image: local/sandglass
    restart: always
    env_file:
      - .env.prod
    expose:
      - 3000:3000
    networks:
      - sandglass
      - ingress
    depends_on:
      - sandglass_postgres

  sandglass_cron:
    container_name: sandglass_cron
    build: ./cron
    restart: always
    env_file:
      - .env.prod


volumes:
  sandglass_postgres:
    name: sandglass_postgres

networks:
  sandglass:
    external: true
  ingress:
    external: true
