# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: wacken
      POSTGRES_USER: raut
    volumes:
      - ./private/var/lib/postgresql:/var/lib/postgresql
    ports:
      - 5556:5432

  schlepptop_adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
